### ISSUE TITLE
"Shift" option doesn't accept zero

### ISSUE THREAD

**Issue by noltron000** [rehypejs/rehype-shift-heading#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.02

### Steps to reproduce

Use {shift: 0} as an option in the this module.
IE,
```js
const vFile = await rehype( )
  .use(rehypeParse, {fragment: true})
  .use(rehypeShiftHeading, {shift: 0})
  .use(rehypeSanitize, rehypeSanitizerSchema)
  .use(rehypeReact, rehypeReactOptions)
  .process(html)
```

### Expected behavior

It shouldn't throw an error, even though technically the function shouldn't do anything to the tree either, with a shift value of zero.

### Actual behavior

There is an error thrown: ``Error: Missing required `shift` in options``.

You can see why this behavior is happening: https://github.com/rehypejs/rehype-shift-heading/blob/5bab36b2c635b0206dae642a62898433c30a8e74/index.js#L18

Zero is falsey, so it isn't an accepted value.

**Comment by noltron000** [comment]
As to why we would want this, there are times our HTML headings might be on the right level already, and other times where it is not. We could pass in a variable shift value instead of setting it at zero as I did in the ticket above. (IE `(html, shift) => rehype( ).use(rehypeShiftHeading, {shift})` or something)

**Comment by wooorm** [comment]
Yeah that was my next question lol. Open to a PR for this, I understand the use case :)

**Comment by noltron000** [comment]
Yeah! No problem and thanks for the fast response. Its not a big deal and can be worked around by setting the options object to `false` to turn the plugin off, instead of `{shift: 0}` or whatever, for example

```js
const processHTML = async (
  html: string,
  options?: Options,
) => {

  // ...

  // Bypass zeroes not being accepted in this method.
  let shiftHeadingOptions
  if (options?.shift == null || options.shift === 0) shiftHeadingOptions = false
  else shiftHeadingOptions = {shift: options.shift}

  // ...

  const vFile = await rehype( )
    .use(rehypeShiftHeading, shiftHeadingOptions)
    .use( // ...etc
}
```

**Comment by wooorm** [comment]
For the PR: you should add a test, and then: don't walk the tree on 0, that would be useless!

**Comment by wooorm** [comment]
done!
